# dev postgresql
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nven
    ports:
      - "5432:5432"
    # volumes:
    # - ./data/postgres:/var/lib/postgresql/data
    networks:
      - default
    restart: always